# Generated by Django 5.1.4 on 2025-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('isPinned', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startDateTime', models.DateTimeField(blank=True, null=True)),
                ('endDateTime', models.DateTimeField(blank=True, null=True)),
                ('classes', models.CharField(choices=[('toate', 'IX-XII'), ('cls 9', 'IX'), ('cls 10', 'X'), ('cls 11', 'XI'), ('cls 12', 'XII')], default='toate', max_length=20)),
            ],
        ),
    ]
