# Generated by Django 5.1.4 on 2025-07-17 12:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=64)),
                ('continut', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data_publicare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
