# Generated by Django 5.1.4 on 2025-07-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_categorie_anunt_status_anunt_views_anunt_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunt',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
