# Generated by Django 5.1.4 on 2025-07-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_anunt_ispinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anunt',
            old_name='isPinned',
            new_name='Important',
        ),
    ]
