# Generated by Django 5.1.4 on 2026-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_ispinned_anunt_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('page', models.CharField(max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
