# Generated by Django 5.1.4 on 2026-07-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
