# Generated by Django 5.1.4 on 2026-07-14 11:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('basic_info', 'General'), ('admitere', 'Admitere'), ('examen', 'Examene'), ('burse', 'Burse'), ('cereri-tip', 'Cereri'), ('others', 'Alta problema')], default='basic_info', max_length=32)),
                ('titlu', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=64)),
                ('important', models.BooleanField(default=False)),
                ('continut', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
