# Generated by Django 5.1.4 on 2026-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
