# Generated by Django 5.1.4 on 2026-07-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_chatsession_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='continut',
            field=models.TextField(),
        ),
    ]
