# Generated by Django 5.1.4 on 2026-07-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_chatsession_continut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(choices=[('Limba și literatura română', 'Limba și literatura română'), ('Limba engleză', 'Limba engleză'), ('Limba franceză', 'Limba franceză'), ('Matematică', 'Matematică'), ('Fizică', 'Fizică'), ('Chimie', 'Chimie'), ('Biologie', 'Biologie'), ('Istorie', 'Istorie'), ('Geografie', 'Geografie'), ('Științe socio-umane', 'Științe socio-umane'), ('Educație vizuală', 'Educație vizuală'), ('Educație fizică și sport', 'Educație fizică și sport'), ('Informatică și TIC', 'Informatică și TIC'), ('Religie', 'Religie')], max_length=100)),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
    ]
