# Generated by Django 5.1.4 on 2026-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Titular', 'TITULAR'), ('', '')], default='Titular'),
        ),
    ]
