# Generated by Django 5.1.4 on 2026-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Titular', 'TITULAR'), (' ', ' ')], default='Titular'),
        ),
    ]
