from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('calendar/', views.calendar, name='calendar'),
    path('contact/', views.contact, name='contact'),
    path('despre/', views.despre, name='despre'),
    path('admitere/', views.admitere, name='admitere'),
    path('contact/contact-form', views.contact_form, name='contact_form'),
    path('orar/', views.orar, name='orar'),
    path('admin_cnu/', views.admin_cnu, name='cnu_admin'),
    path('publicatii/', views.publicatii, name='publicatii'),
    path('publicatii/noutati/', views.noutati, name='noutati'),
    path('publicatii/activitati', views.activitati, name='activitati'),
    path('publicatii/proiecte/', views.proiecte, name='proiecte'),
    path('unpin/', views.unpin, name='unpin'),
    path('publicatii/<int:publicatie_id>/', views.publicatie, name='publicatie'),
    path('bacalaureat/', views.bacalaureat, name='bacalaureat'),
    path('personal_didactic/', views.personal_didactic, name='personal_didactic'),
    path('personal_auxiliar/', views.personal_auxiliar, name='personal_auxiliar'),
    path('personal_nedidactic', views.personal_nedidactic, name='personal_nedidactic'),
    path('hotarari/', views.hotarari, name='hotarari'),
    path('echipa/', views.echipa, name='echipa'),
    path('documente/', views.documente, name='documente'),
    path('cereri/', views.cereri_tip, name='cereri'),
    path('burse/', views.burse, name='burse'),
    path("chatbot/", views.chatbot, name="chatbot"),
    path("chatbot/message/", views.chatbot_message, name="chatbot_message"),
    path("api/search/", views.search_api, name="search_api"),
    path("search/", views.search_page, name="search"),
]